### ISSUE TITLE
[feat] myPage rank stat api와 기능 변경에 따른 수정사항

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#113]
## Desc

1개의 api가 4개로 쪼개짐니다..!
record와 rank는 Null이 올 수 있고, tier가 생겼습니다..!!
## Detail

Before ->
GET /users/{nickname}/stat
After ->
GET /users/{nickname}/stats/season
GET /users/{nickname}/stats/total
GET /users/{nickname}/ranks/season
GET /users/{nickname}/ranks/total
tier가 Doctor인 경우에만 record와 rank를 표시해주고, 나머지는 null/null로 한다.
## Todo
- [ ] GET 요청 조개기
- [ ] doctor 이외의 경우에 null 처리
- [ ] doctor인 경우 혹시 null 들어오면 어떡계
