### ISSUE TITLE
[feat] 친구 / 차단 요청 버튼에 달기 

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#118]
## Desc

친구 / 차단 요청 버튼에 달기
## Detail

요청이 구현은 안되어 있지만 버튼에 달기
## Todo
- [ ] POST /users/friends/{nickname}
- [ ] DELETE /users/friends/{nickname}
- [ ] POST /users/blocks/{nickname}
- [ ] DELETE /users/blocks/{nickname}
