### ISSUE TITLE
[feat] 로그인/인증 관련 여러가지

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#139]
## Desc

로그인과 인증 관련해 조금 손을 댑니다.
## Detail

로그인이 잘 작동되도록 애써봅시다.
## Todo
- [x] setCookie시에 만료 시간 넣어주기. 일단 1시간 후로!
- [x] 훅에 만들어놓은 부분으로 대체할 부분 대체하기
- [x] 로그인 기능 테스트해 볼 수 있는 MockApi 만들기
