### ISSUE TITLE
[feat] friends page

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#149]
## Desc

노는게제일좋아
## Detail

모여라 친구들
friend request block 세 개의 탭으로 이루어진 페이지입니다.
## Todo
- [x] 컴포넌트 만들기
- [x] css로 위치 잡기
- [x] mock api 만들고 요청 붙이기
- [x] translation 준비하기
- [x] Request 탭 pending으로 바꾸기
