### ISSUE TITLE
[feat] Channels 페이지 API 및 기능 구현

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#156]
## Desc

channel 페이지의 틀은 잡혔으니 이제 본격적인 채널 기능들을 구현해보겠습니다

## Detail

최신순/인기순 정렬과 채널 관련 API 요청을 만들어 mock data를 불러왔을 때 실제로 적용시켜보기

## Todo
- [x] 최신순/인기순 정렬 적용
- [x] fetch로 GET 했던 channelsList React Query로 수정
- [x] 채널 새로고침 만들기
- [x] 채널 검색 API 만들기
- [x] 채널 생성 API 틀 잡아놓기
- [x] 채널 입장 API 틀 잡아놓기
