### ISSUE TITLE
[refactor] myPage components 리팩토링

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#16]
## Desc

코드리뷰 받은 것을 기반으로 myPage의 component들을 리팩토링 합니다.
## Todo
- [x] recoil 사용해서 EditableStatus 빼기
- [x] goTo 탭 map 쓰도록 리팩토링하기 && onWhichTab을  key/value로 해보기
- [x] 과도하게 분리된 컴포넌트 모으기모으기
