### ISSUE TITLE
[feat] 새로운 Channel 생성

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#162]
## Desc

유저는 새로운 채널을 생성할 수 있습니다

## Detail

새로운 채널을 만들기 위해서는 채널 페이지 상단에 + 버튼을 누릅니다.
그러면 채널 정보를 기입할 수 있는 모달이 뜹니다.
채널 title, access(public / protected / private), 최대 수용인원을 설정하고 생성

## Todo
- [x] ChannelSearch, ChannelSetting 컴포넌트 하나로 합치기
- [x] 모달 구조 파악 & 생성
- [x] mock API 만들기
