### ISSUE TITLE
[feat] axios 세팅하기~~!

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#17]
## Desc

axios.ts 파일을 만듭니다.
## Detail

아직 베이스 유알엘에 대한 env 설정을 안했습니다. 향후 필요!
## Todo
- [x] axios.ts 만들기
- [ ] 헤더 설정 만들기~!
- [ ] 환경변수로 base_url 받아오기~~!!
