### ISSUE TITLE
[feat] 각 Channel을 Page로 관리하자

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#173]
## Desc

`/channels` 페이지에서 채널 박스를 선택했을 때 해당하는 채널의 페이지로 이동합니다

## Detail

NextJS의 dynamic routes를 이용하여 channel의 채팅 페이지를 구성합니다

## Todo
- [x] 채널 폴더 구조 변경하기
- [x] 각 채널 클릭 시 해당 채널의 페이지로 이동
- [x] 채널 입장 API 만들기
- [x] Mock API 만들기
