### ISSUE TITLE
[feat] Channel 참여 목록 리스트 

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#174]
## Desc

각 채널에서는 세팅이 있는데요, 채널 참여 목록 리스트를 볼 수 있고 친구도 초대할 수 있답니다.

## Detail

세팅 버튼을 누르면 사이드 바를 통해 채널 참여 목록 리스트가 나옵니다.
내가 맨 위에 배치되고 나머지 참여자들이 알파벳 순으로 정렬됩니다.
내 권한에 따라 admin / kick / ban /mute를 할 수 있습니다.
참여자를 누르면 프로필 모달이 뜹니다.
초대하기 버튼을 누르면 해당 채널에 친구를 초대할 수 있습니다.

## Todo
- [x] 알림의 사이드 바 참고하여 사이드 바 만들기
- [x] 참여자 목록 리스트 컴포넌트 만들기
- [x] 친구 초대 / 나가기 버튼
