### ISSUE TITLE
[feat] invitation 수락/거절 기능 구현

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#178]
## Desc

invitation 수락/거절 기능 구현

## Detail

이후 스프린트로 밀려났지만 지금 당장 할 수 있는 것들만 처리해보고자 합니다..

## Todo
- [x] 초대 거절 api 코드 추가
- [x] next api 추가
- [x] invitation 목록을 상태로 관리하여, 초대 거절 시 뷰에서 초대가 삭제되도록 구현
