### ISSUE TITLE
[feat] 게임 페이지 구현

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#213]
## Desc

정해진 건 하~~~나도 없지만
뷰를 만들어 놓고 보자~!

## Detail

탁구채 금지

## Todo
- [x] 페이지 기본 구성
- [ ] 요청 달고 웨이팅 모달?팝업?토스트? 만들기
- [ ] 건우랑 초대창 만들기
