### ISSUE TITLE
[feat] Channel 나라의 카스트제도

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#214]
## Desc

각 채널은 신분사회입니다.
Owner -> Administrator -> Normal 순

## Detail

Owner는 모든 참여자에게 admin 권한 부여 / 해제, kick, ban, mute, unmute 할 수 있습니다.
Administrator는 Owner를 제외한 모든 참여자에게 kick, ban, mute, unmute 할 수 있습니다.
Normal은 바베큐맛 쫄병입니다.
하지만 마음에 들지 않는다면 채널을 나갈 수 있습니다.

## Todo
- [x] 채널 참여자 목록 사이드바에서 admin/kick/ban/mute 버튼에 요청 붙이기 ⇒ alert
- [x] admin/kick/ban/mute mock api 맨들기
- [x] 채널 퇴장 요청
