### ISSUE TITLE
[feat] 클래식 퐁게임을 만들어보자

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#235]
## Desc

single player 퐁게임을 만들어보자

## Detail

일단 정상적으로 동작하는 1인용 퐁게임을 만들어보겠습니다.
일반적인 퐁게임은 가로로 플레이하지만 가능하다면 세로로 플레이 할 수 있게 해보겠습니다.
베타 버전입니다.

## Todo
- [x] 캔버스로 퐁 테이블 그리기
- [x] 벽에 맞을 때만 공이 튕기게 연산하기
- [x] 5라운드가 끝나면 게임 종료
- [x] 프로필 컴포넌트
- [x] 이모지 컴포넌트
