### ISSUE TITLE
[fix] 채팅 전송 에러 고치기 

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#242]
## Desc

채팅이 잘 안가요..

## Detail

채팅 보내기 & 채팅 받아오기 살짝씩 문제가 있는데 찾아서 고쳐볼게요옷

## Todo
- [x] 채팅 전송 에러 고치기 (chats 상태에 메시지가 여러번 추가되고 있는 것 같습니다.)
- [x] 전송 실패 메시지의 재전송/삭제 버튼 고치기
- [x] 채팅 fetch isBottomRefVisible일 때 계속 받아와지는 것 수정하기
- [x] 채널에 입장했을 때 최초에는 채팅 내역을 잘 불러오는데 query key가 caching되어 2번째부터는 채팅 내역을 안보여주는 문제 해결
- [x] 채널 생성 시 body 안에 객체로 감싼거 벗겨주기 (채팅에 채널 꼽사리 좀 끼겠습니다..! 아주아주 사소한 수정)
