### ISSUE TITLE
[fix] api 합쳐보면 비로소 보이는 수정사항들

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#247]
## Desc

api 합체 프로토콜을 해봤는데요, 열심히 했어요.
근데 수정사항들이 조금 있더라구요?
백이랑은 일단 개인정비 하고 다시 만나기로 했어요.
그래서 이거 다 고쳐도 아모른직다.

## Detail

- `SearchBar`의 `handleOnSubmit`이 옵션인 경우 `e.preventDefault()`이 없다.
- 주소창에 `/signUp` 대놓고 접근하면 접속되는 문제
- 최초 로그인 시 `/signUp`으로 바로 리다이렉트가 안되는 문제
- `useAuthHandler`에서 `setCookie` 할 때 Bearer 떼기 (axios 파일에도 Bearer가 있어서 겹침)
- 새로고침하면 `login state`가 관리가 안되서 아예 `LoginFilter`에서 `users/me`를 보고 state 업데이트
- 로그아웃 시 모달 닫아주어야 함
- 내가 속한 채널이 protected이고 채널 리스트에서 내 채널 들어가면 비번 치는 모달 나오지마

## Todo
- [x] 친구 검색하는 SearchBar의 handleOnSubmit 수정
- [x] 주소창으로 `/signUp` 접근하는거 막기
- [x] 최초 로그인 시 `/signUp`으로 리다이렉트
- [x] useAuthHandler에서 setCookie 수정
- [x] LoginFilter에서 `users/me`로 login state 업데이트
- [x] 로그아웃 시 모달 닫기
- [x] 내가 속한 채널을 채널 리스트에서 들어갈 때는 비번 모달 안띄우기
