### ISSUE TITLE
[fix] 3차 합치기 때 발견한 수정 사항

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#258]
## Desc

3차 합치기 때 발견한 수정 사항

## Todo
- [ ] 1. 기존 채널이 있을 때 다른 채널로 들어가면 기존 채널에서 나가진다고 경고 알림 띄워주기 yes / no
- [ ] 2. 친구 / 불낙 등 요청시에 invalidate query 잘 해주기 → 소켓 없이 관리
- [ ] 3. Noti 친구 요청 request count 적용 안됨 → 왜지?
- [ ] 4. 채널 / 게임 초대 받으면 페이지 이동 → router push 해버리기
- [ ] 5. 채팅 400으로 실패 시에 다시보내기가 뜨는건 이상하지 않나? 라는 의견. 네트워크 오류 시에만 할까요? → 좋아요 근데 어케하지?
- [ ] 6. 채팅방에 없는 유저 기본이미지 넣어주기 (유 령) → 42byte에는 유령이 살고 있다
- [ ] 7. 게스트일때 사이드바 열 수 있어서 거기 요청이 항상 실패함 → 게스트일때 안보여줘?버려?
