### ISSUE TITLE
[feat] myPage Patch 요청 구현 

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#29]
## Desc

GET은 만들었지만 나머지를 해야합니다!
## Detail

myPage에서 필요한 api들 중 아래 항목들을 구현합니다.
## Todo
- [x] PATCH /users/{nickname}/detail
- [x] 위 요청을 위해 필요한 드롭다운 만들기
- [x] PATCH /users/{nickname}/achievements
- [x] PATCH /users/{nickname}/emojies
