### ISSUE TITLE
[feat] 이미지, 폰트 등의 것들 확정하기

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#293]
## Desc

이미지, 폰트 등의 것들 확정하기

## Detail

achievement, emoji, profile 등의 이미지를 확정할 때가 되었습니다.

## Todo
- [x] achievement 목록 정하기
- [x] emoji 목록 정하기
- [x] 폰트 정하기
- [x] 프로필 이미지 정하기
