### ISSUE TITLE
[feat] 게임 이모찌모찌

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#307]
## Desc

게임 중 이모지를 누르면 이모지가 빵하고 튀어나와야 합니다만?

## Detail

프로필 이미지 위에 이모지가 나오면 참 좋을 것 같아요.

## Todo
- [x] 내 이모지는 내 프로필 이미지에
- [x] 그대의 이모지는 그대의 프로필 이미지에
- [x] 애니메이션을 적용시키면 참 좋겠다.
