### ISSUE TITLE
[fix] 한결이 형 괴롭힌 소켓 누구야

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#308]
## Desc

채팅 소켓이 자꾸 말썽을 부립니다.
연결 상태가 불안정해요.
한결이 형 속이 타들어갔어요.

## Detail

채팅 소켓 옥상으로 따라와

## Todo
- [x] 연결이 불안정한 이유 분석
- [x] 디엠이랑 노티 빨간불이 꺼지지 않는 현상 해결하기!
- [x] autoConnection을 false로 해놨을 때 connect를 해도 가끔 연결이 잘 안됨
