### ISSUE TITLE
[feat] Game을 무리마하러 왔다

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#341]
## Desc

게임의 기본 기능은 얼추 구현이 다 된 것 같아요~!

## Detail

이제 최적화와 스타일, 모드 확정하기, 기능 개선하기 등등을 해보겠습니다!

## Todo
- [x] 창 크기 조정했을 때 바 위치가 자리를 찾아가지 못하는 건에 대하여
- [x] 매치 프로필, 이모지 컨포넌트 반응형 처리
- [x] queue socket도 <SocketManager> 사용해보기
- [x] 이제는 모드 진짜 확정 지을 때가 됐다!!
