### ISSUE TITLE
[fix] 업적 = 엎어모달, 프로필모달에서 히스토리 누르면 모달 끄기 

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#358]
## Desc

업적 모달을 킬 때 프로필 모달이 꺼집니다. 업적을 엎어모달로.
프로필 모달에서 히스토리 누르면 히스토리로 가지는데 모달이 남아있습니다. 끄기

## Detail

여타 jot버그가 있다면 그거도 처리
## Todo
- [x] 업적 엎어 모달
- [x] 프로필 모달과 히스토리
- [x] 히스토리 링크 문제가 있다..! 수정
