### ISSUE TITLE
[feat] 다중탭을 처리해라!!!

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#359]
## Desc

다중 소켓연결은 허용하지 않는다.

## Detail

이미 접속 중인 탭을 배신하고 새로운 탭으로 접속하면
기존 탭은 로그아웃 시키고 새로 연결된 소켓을 유지한다.

## Todo
- [x] 소켓 이벤트 회의
- [x] 새로 접속했는데 진행 중인 게임이 있는 경우 게임룸으로 유도하는 모달
- [x] 새로운 소켓이 연결된 경우 기존 소켓은 끊고 로그아웃을 유도하는 모달
