### ISSUE TITLE
[fix] QA하면서 발견한 문제들 

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#419]
## Desc

다 같이 QA 하면서 발견한 자잘한 문제들을 고쳐보겠습니다~~!

## Detail

크리티컬한 문제들은 아님!

## Todo
- [x] 채팅창에서 nickname `cursor: pointer` & `width: fit-content`
- [x] mute input box 더 잘 보이게 손보기
- [x] mute가 된 상태에서 다시 들어오면 (leave→join 아님) mute status 모름
- [x] game roomId 유효성 검사
