### ISSUE TITLE
[feat] Settings 페이지 구현

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#42]
## Desc

Settings 페이지 구현

## Todo
- [x] 언어 설정 가능하도록 구현
- [ ] 2차 인증 설정 구현
- [ ] api 요청 구현
