### ISSUE TITLE
[feat] 게임 소켓 이벤트 통합 및 데이터 추가

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#444]
## Desc

게임과 관련된 소켓 이벤트 대청소🧹

## Detail

- 게임 페이지를 제외한 멀티탭 접속 허용 (게임 소켓은 하나만 연결)
- 게임 중간에 재접속한 유저를 위해 `initData` 이벤트에 현재 점수 데이터 추가
- 통합할 수 있는 이벤트들은 합쳐서 이벤트 줄이기
- 이벤트 이름 변경

## Todo
- [x] `multiConnect` 이벤트 namespace `/game`으로 옮기기
- [x] `handshake` -> `joinGame` (client -> server)
- [x] `handshake` -> `invalidGameId` (server -> client)
- [x] `joinGame` -> `matched`
- [x] `matchInfo` -> `userInit` (데이터 추가: 나와 상대방의 nickname, title, imgUrl)
- [x] `initData` -> `gameInit` (데이터 추가: 나와 상대방의 score 추가)
