### ISSUE TITLE
[feat] 업적 문구 추가하기 & 채널 에러 메시지 맞추기

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#451]
## Desc

업적 문구 추가하기

## Detail

채널 에러 메시지는 백엔드껄 수정하는걸로..

## Todo
- [x] 업적 문구 추가하기
- [x] 백엔드 에러 메시지 프론트랑 맞추기
- [x] 킥밴 메시지 안나오는거 고치기
