### ISSUE TITLE
[style] 좀좀따리 스타일 수정하기

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#462]
## Desc

마무리를 해봅시다!

## Detail

여기저기 거슬리던 스타일들을 마무리할거에요

## Todo
- [x] RankTag 전체적으로 다
- [x] Settings 버튼 위치
- [ ] Settings에 이베일과 저작권 머시기 넣기
- [x] UserBox 오른쪽 버튼 위치
- [x] 게임 페이지
- [x] seletableItems 보더 뚝딱거리는거 고치기
