### ISSUE TITLE
[fix] 임방시편으로 연결해 놓은 소켓을 해결할 때가 되었다

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#472]
## Desc

평가를 받기 위해 임방시편으로 처리해 놓은 소켓을 고쳐보겠습니다.

## Detail

챗 페이지 <-> 친구 페이지 이동 간에 발생하는 소켓 문제는 프로필 모달에 게임 초대 버튼을 넣으려다보니 생긴 문제였습니다.
온라인인 친구의 프로필 모달에 게임 초대 버튼을 없앰으로 인해 소켓 문제는 자연스럽게 소멸되었습니다.
그 외에 소켓을 이용한 부분에서 미흡했던 예외 처리도 몇가지 끼워넣었습니다.

## Todo
- [x] 프로필에 게임 초대 버튼 없애기
- [x] 게임이 진행중일 때 다른 탭에서 로그인 했을 때 기존에 게임이 진행중이던 탭에는 `useIsInGameModal` 안띄우기
- [x] 상대방이 게임 초대 거절했을 때 거절 alert 띄워주기
- [x] 이미 큐가 돌아가고 있거나 이미 게임중일 때 큐 입장하려하면 그에 맞는 에러 메시지 띄워주기
