### ISSUE TITLE
[fix] 광고 위치 변경 때문에 생기는 이슈들 총망라

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#488]
## Desc

윈도우 가로 크기에 따라 광고 위치가 column 또는 row로 설정되는데요,
현재 레이아웃 특성상 AdsLayout이 내부 컴포넌트들을 모두 감싸고 있기 때문에
컴포넌트들이 전부 리랜더링되면서 생기는 이슈들이 몇 가지 있습니다.

## Detail

마이 페이지에서 탭이 초기화 됩니다.
게임 및 챗 페이지 모바일 뷰에서는 광고가 들어갈 자리가 없습니다.

## Todo
- [x] 마이페이지 탭 초기화 안되게 하기
- [x] 게임 로비에서 normalClicked 초기화 안되게 하기
- [x] 게임 챗 페이지 모바일에서는 광고 떼기

## Etc
알고보니 AdsLayout에서 children이 조건부 렌더링에 영향을 받고 있었기 때문에 리랜더링 되는 것이었습니다...
따라서 children을 조건문 밖에 위치해주었더니 해결되었지만 리턴문이 조금 난잡해졌습니다.
