### ISSUE TITLE
[fix] 난 채널에 BAN된 친구를 초대해

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#490]
## Desc

채널에 ban된 친구를 초대하면 초대 받은 친구가 수락해도 채널에 들어가진 못하는데 처리가 살짝 미흡합니다.

## Detail

수락했을 때 해당 채널에 ban 되어있다는 메시지 띄워주고 toast를 없애주고 알림도 없애주면 좋을 것 같아요.
알림 사이드 바가 열려있을 때는 토스트 안 띄워주는 부분도 잘 안되서 수정 좀 해보겠습니다.

## Todo
- [x] 수락 시 에러 메시지 띄워주기
- [x] 메시지 띄워주고 토스트기 전원 뽑기
- [x] 알림에 빨간불 계속 들어와 있으니 알림통도 비워주기
- [x] 게임 / 채널 초대로 페이지 이동 시 모달과 사이드 바 닫아주기
- [x] 알림 사이드 바 열려있을 때 토스트기 전원 뽑기
