### ISSUE TITLE
[style] 모바일일 때 어긋나는 스타일들 수정

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#528]
## Desc

꽤나 많이 어긋납니다.

## Detail

매의 눈으로 찾아라

## Todo
- [x] 친구창 width 너무 큼
- [x] 기타 등등 word-break 추가
- [x] 404 페이지
- [x] mypage 프로필 사진 edit 버튼 위치
