### ISSUE TITLE
[fix] 로그인 http only

### ISSUE THREAD

**Issue by keonwoo98** [Dr-Pong/dr_pong_client#536]
## Desc

쿠키를 http only 방식으로 사용해야 JS에서 쿠키에 접근하지 못해요.
그러기 위해선 백에서 http에 쿠키를 세팅해주어야 합니다.
그렇게 하면 api 요청 시 header에만 담아주면 된답니다.

## Detail

하지만 도메인 불일치 문제인지 잘 되질 않아요.
그렇다면 localStorage을 사용하는 방법도 있답니다.

## Todo
- [ ] 백에서 웹에 쿠키 세팅이 가능한지 확인하기
- [ ] 그에 따라 클라이언트 코드 수정하기
- [ ] 안되면 localStorage에 쿠키 저장
