### ISSUE TITLE
[fix] 모달 수정 및 스타일 추가

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#65]
## Desc

업적 모달 작업 중 모달이 이렇게 변하면 좋겠다 싶어서 수정합니다.
## Todo
- [x] handleBackdropClick에 리셋 추가
- [x] ModalPhrase가 children 받게 수정
- [x] 글자 색을 거멓게
