### ISSUE TITLE
[fix] myPage 사소한 수정사항들

### ISSUE THREAD

**Issue by triplecheeseburger** [Dr-Pong/dr_pong_client#75]
## Desc

백과 붙이면서 찾은 문제점들입니다.
## Detail

1. SelectTab 컴포넌트가 마운트될 때 patch 가 요청된다! 이유는, useEffect에서 초기 상태를 array의 길이를 보고 판단해 길이가 0이면 얼리 리턴을 해줬는데 명세가 바뀌며 초기 상태가 [null, null, null]이 되면서 문제가 생겼습니다.
2. ProfileCard 컴포넌트에서 Title이 null로 오는 경우에도 title.id에 접근해서 에러가 생겼습니다. title 자체가 Null 인 경우도 검사합니다.
3. 이모지 숫자가 4개로 바뀌어서 Mock api 수정했습니다. 
## Todo
- [x] SelectTab 마운트시 patch 안되게 수정
- [x] ProfileCard에서 title 널 검사
- [x] 이모지 api selected를 4개로 수정
