### ISSUE TITLE
[feat] 프로필 모달 만들기

### ISSUE THREAD

**Issue by tamagoyakii** [Dr-Pong/dr_pong_client#95]
## Desc

프로필 모달 구현
## Todo
- [x] 모달에 Profile.tsx 넣기
- [x] 버튼 컴포넌트 만들기
- [x] next api 추가
